### ISSUE TITLE
Fix code quality CI has "Partial class with single part in class.cs" issue.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/osu-framework-microphone#336]
For example(#332)

<img width="1143" alt="image" src="https://github.com/karaoke-dev/osu-framework-microphone/assets/9100368/af31a9d4-93cd-48f9-9c33-406b595d6362">

Got this issue in the CI error.

Should check about:
- [ ] Why there's no similar issue in the o!f
- [ ] How to fix that(e.g should compile the project first?)

**Comment by smoogipoo** [comment]
We updated the DotSettings file for this: https://github.com/ppy/osu-framework/commit/9f3bc03cb930fd0a4c7af13c148b5d5504b6043e

**Comment by andy840119** [comment]
Nice mention 👍🏼
